version: "3"
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true #optional
    volumes:
      - ./data:/app/jackett/data
      - ./downloads:/app/jackett/downloads
    ports:
      - "9117:9117"
    restart: unless-stopped
  web:
    
    build: .
    depends_on:
      - jackett

    command: sh -c "uvicorn Api:app --reload --port=8000 --host=0.0.0.0"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./Config:/Config
    restart: unless-stopped
volumes:
  config:
    external: true
